### PR TITLE
Print error message on missing configuration file

### PR DESCRIPTION
**Pull request by michaeljoseph**
If you run `towncrier` directly after installing it, you get:
```
$ towncrier --draft
Loading template...
Traceback (most recent call last):
  File "/Users/michael/.pyenv/versions/3.5.1/envs/mould/bin/towncrier", line 11, in <module>
    sys.exit(_main())
  File "/Users/michael/.pyenv/versions/3.5.1/envs/mould/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/michael/.pyenv/versions/3.5.1/envs/mould/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/michael/.pyenv/versions/3.5.1/envs/mould/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/michael/.pyenv/versions/3.5.1/envs/mould/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/michael/.pyenv/versions/3.5.1/envs/mould/lib/python3.5/site-packages/towncrier/__init__.py", line 38, in _main
    return __main(draft, directory, project_version, project_date, answer_yes)
  File "/Users/michael/.pyenv/versions/3.5.1/envs/mould/lib/python3.5/site-packages/towncrier/__init__.py", line 50, in __main
    if config['template'] is None:
TypeError: 'NoneType' object is not subscriptable
```

This PR displays an error message for this scenario:
```
$ towncrier
Loading config...
Missing configuration: towncrier requires an appropriately configured pyproject.toml file.
```

### CODE REVIEW

**Comment by michaeljoseph** [comment]
:bell: @hawkowl would you like me to have a go improving coverage so we can merge this?

**Comment by hawkowl** [comment]
@michaeljoseph Yes please! Sorry that I've dropped the ball on this.

**Comment by michaeljoseph** [comment]
This seems taken care of by #145 now, closing.

**Comment by michaeljoseph** [comment]
And tbh defaulting the config instead of throwing an Exception is _much_ nicer 👍

**Pull request closed without merging**
