### PR TITLE
Add a `major` fragment

### PR DESCRIPTION
**Pull request by acabarbaye**
See issue #132

### CODE REVIEW

**Comment by kinkerl** [comment]
i woud love to see this upstream. i would have used this today :)

**Comment by davidhyman** [comment]
@acabarbaye this PR needs a newsfile 🙂

**Comment by acabarbaye** [comment]
@hawkowl : Could you have a look at this PR so that it can be merged ?

**Comment by hawkowl** [comment]
The existing defaults are matching Twisted's model, which I'm not sure I want to change.

You probably just want to configure it per-project, as attrs does it? https://github.com/python-attrs/attrs/blob/master/pyproject.toml

**Pull request closed without merging**
