### PR TITLE
Add 'towncrier create', 'towncrier check' commands

### PR DESCRIPTION
**Pull request by stephenfin**
This rather chunky PR adds support for subcommands, allowing us to add a create command to automatically create news fragments.

### CODE REVIEW

**Comment by stephenfin** [comment]
@hawkowl Anything I can do to help move this along?

**Comment by hawkowl** [comment]
@stephenfin Hi! I only just noticed this (drowned under GitHub notifications). I have added it to my todoist to review :)

**Comment by hawkowl** [comment]
@stephenfin (overall from a browse it looks good, if there's any changes I want I'll likely fix them up myself before merging)

**Comment by stephenfin** [comment]
Sweet. Let me know if you need anything from me :+1:

**Comment by stephenfin** [comment]
@hawkowl Friendly ping :smile:

**Comment by hawkowl** [comment]
Thanks!

**Comment by stephenfin** [comment]
@hawkowl Any chance of getting a release cut with this, please? 😊

**Pull request merged**
